# Generated by Django 3.2.12 on 2023-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSP', models.CharField(max_length=30)),
                ('LoaiSP', models.CharField(max_length=30)),
                ('GiaSP', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('DanhGia', models.FloatField()),
                ('LuotMua', models.IntegerField()),
                ('TonKho', models.IntegerField()),
            ],
        ),
    ]
