# Generated by Django 3.2.12 on 2023-05-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='DanhGia',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='LuotMua',
        ),
    ]
