# Generated by Django 3.2.12 on 2023-05-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='LoaiSP',
        ),
    ]
