# Generated by Django 3.2.12 on 2023-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0006_auto_20230517_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
