# Generated by Django 3.2.12 on 2023-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0009_auto_20230518_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='MoTa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
