# Generated by Django 3.2.12 on 2023-05-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0010_sanpham_mota'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='SDT',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
