# Generated by Django 3.2.12 on 2023-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0014_alter_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='category',
            field=models.ManyToManyField(related_name='sanpham', to='app_ban_hang.Category'),
        ),
    ]
