# Generated by Django 3.2.12 on 2023-05-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0015_sanpham_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='LoaiSP',
        ),
    ]
