# Generated by Django 3.2.12 on 2023-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0016_remove_sanpham_loaisp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='LoaiSP',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
