# Generated by Django 3.2.12 on 2023-05-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0017_sanpham_loaisp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='LoaiSP',
        ),
    ]
