# Generated by Django 3.2.12 on 2023-05-22 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ban_hang', '0018_rename_category_loaisp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='DonHang',
        ),
    ]
