# Generated by Django 3.2.12 on 2023-05-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0019_rename_order_donhang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='DatHang',
        ),
    ]
