# Generated by Django 3.2.12 on 2023-05-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0020_rename_orderitem_dathang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatHang',
            new_name='Orderitems',
        ),
    ]
