# Generated by Django 3.2.12 on 2023-05-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0021_rename_dathang_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderitems',
            new_name='Orderitem',
        ),
    ]
