# Generated by Django 3.2.12 on 2023-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0025_lienhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuVanNoiThat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.TextField()),
            ],
        ),
    ]
