# Generated by Django 3.2.12 on 2023-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0027_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='SDT',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
