# Generated by Django 3.2.12 on 2023-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0028_alter_base_sdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='DiaChiCuaHang',
        ),
        migrations.AlterField(
            model_name='base',
            name='DiaChi_Khac',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='HoTroKhachHang',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='LienHeChungToi',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
