# Generated by Django 3.2.12 on 2023-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0029_auto_20230529_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='DiaChi_Khac',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='HoTroKhachHang',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='LienHeChungToi',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
