# Generated by Django 3.2.12 on 2023-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0030_auto_20230529_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='LuotMua',
            field=models.IntegerField(default=0),
        ),
    ]
