# Generated by Django 3.2.12 on 2023-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0031_sanpham_luotmua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
