# Generated by Django 3.2.12 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0032_carousel_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel_home',
            name='img_active',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
