# Generated by Django 3.2.12 on 2023-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ban_hang', '0036_alter_blog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='LuotLike',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='SoCmt',
        ),
    ]
